/var/log/praesidium/nftables.log {
    size 50M
    missingok
    rotate 7
    compress
    delaycompress
    notifempty
    create 640 syslog adm
    postrotate
        kill -HUP $(pidof rsyslogd)
    endscript
}
