# Aplicador WireGuard: copia configs validadas a /etc/wireguard y gestiona wg-quick.
# WireGuard applier: copies validated configs to /etc/wireguard and manages wg-quick.
# Solo toca interfaces marcadas como gestionadas por Praesidium y mantiene rollback.
# It only touches interfaces marked as Praesidium-managed and keeps rollback.

import json
import shutil
import subprocess
from pathlib import Path
from task_update_json import task_update_json

OUTPUT_DIR = Path('/var/lib/praesidium/running/wireguard')
GENERATED_DIR = OUTPUT_DIR / 'generated'
MANIFEST = OUTPUT_DIR / 'manifest.json'
ACTIVE_DIR = Path('/etc/wireguard')
MANAGED_MARKER = 'Managed by PraesidiumFirewall'


# Registra un fallo de apply WireGuard en el historial del commit y detiene el proceso.
# Records a WireGuard apply failure in the commit history and stops the process.
def _fail(date, task):
    task_update_json(date, task, 'fail')
    raise SystemExit(1)


# Registra un paso de apply WireGuard completado correctamente.
# Records a WireGuard apply step completed successfully.
def _success(date, task):
    task_update_json(date, task, 'success')


# Ejecuta comandos críticos que deben fallar si el sistema devuelve error.
# Runs critical commands that must fail if the system returns an error.
def _run(cmd):
    return subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)


# Ejecuta comandos tolerantes para paradas/deshabilitados idempotentes.
# Runs tolerant commands for idempotent stop/disable operations.
def _run_allow_failure(cmd):
    return subprocess.run(cmd, check=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)


# Carga el manifest generado y valida que contiene la lista de interfaces gestionadas.
# Loads the generated manifest and validates the managed interface list.
def _load_manifest(date):
    # Fase 1: comprobar que el generador dejó manifest antes de tocar /etc.
    # Phase 1: check that the generator left a manifest before touching /etc.
    if not MANIFEST.exists():
        _fail(date, 'wireguard_apply_manifest_exist')

    # Fase 2: parsear manifest y rechazar cualquier estructura inesperada.
    # Phase 2: parse the manifest and reject any unexpected structure.
    try:
        data = json.loads(MANIFEST.read_text(encoding='utf-8'))
    except json.JSONDecodeError:
        _fail(date, 'wireguard_apply_manifest_format')
    interfaces = data.get('managed_interfaces')
    if not isinstance(interfaces, list):
        _fail(date, 'wireguard_apply_manifest_format')
    _success(date, 'wireguard_apply_manifest_exist')
    _success(date, 'wireguard_apply_manifest_format')
    return interfaces


# Detecta si una configuración activa fue generada por PraesidiumFirewall.
# Detects whether an active configuration was generated by PraesidiumFirewall.
def _is_managed_active_conf(path):
    try:
        return path.exists() and MANAGED_MARKER in path.read_text(encoding='utf-8', errors='ignore')[:512]
    except OSError:
        return False


# Enumera solo interfaces WireGuard activas gestionadas por Praesidium.
# Lists only active WireGuard interfaces managed by Praesidium.
def _active_managed_interfaces():
    if not ACTIVE_DIR.exists():
        return set()
    return {p.stem for p in ACTIVE_DIR.glob('*.conf') if _is_managed_active_conf(p)}


# Crea backup de configuraciones activas antes de tocar /etc/wireguard.
# Creates a backup of active configurations before touching /etc/wireguard.
def _backup_active(date, interfaces):
    # Fase 1: preparar carpeta rollback asociada al commit actual.
    # Phase 1: prepare a rollback folder tied to the current commit.
    backup_dir = OUTPUT_DIR / f'rollback_{date}'
    backup_dir.mkdir(parents=True, exist_ok=True)
    metadata = {}
    try:
        # Fase 2: copiar configs activas gestionadas y anotar cuáles no existían.
        # Phase 2: copy active managed configs and record which ones were missing.
        for iface in interfaces:
            active = ACTIVE_DIR / f'{iface}.conf'
            if active.exists():
                shutil.copy2(active, backup_dir / f'{iface}.conf')
                metadata[iface] = 'present'
            else:
                metadata[iface] = 'missing'
        # Fase 3: guardar metadata para que rollback sepa restaurar o eliminar.
        # Phase 3: save metadata so rollback knows whether to restore or remove.
        (backup_dir / 'metadata.json').write_text(json.dumps(metadata, indent=2), encoding='utf-8')
        _success(date, 'wireguard_backup_config')
        return backup_dir, metadata
    except OSError:
        task_update_json(date, 'wireguard_backup_config', 'fail')
        return None, {}


# Restaura configuraciones anteriores si falla la aplicación de WireGuard.
# Restores previous configurations if the WireGuard apply step fails.
def _rollback(date, backup_dir, metadata, interfaces):
    try:
        # Fase 1: detener interfaces tocadas antes de restaurar archivos.
        # Phase 1: stop touched interfaces before restoring files.
        for iface in interfaces:
            _run_allow_failure(['sudo', 'systemctl', 'stop', f'wg-quick@{iface}'])
            if metadata.get(iface) == 'present' and backup_dir and (backup_dir / f'{iface}.conf').exists():
                _run(['sudo', 'cp', str(backup_dir / f'{iface}.conf'), str(ACTIVE_DIR / f'{iface}.conf')])
                _run(['sudo', 'chmod', '0600', str(ACTIVE_DIR / f'{iface}.conf')])
                _run(['sudo', 'systemctl', 'start', f'wg-quick@{iface}'])
            else:
                _run(['sudo', 'rm', '-f', str(ACTIVE_DIR / f'{iface}.conf')])
                _run_allow_failure(['sudo', 'systemctl', 'disable', f'wg-quick@{iface}'])
        _success(date, 'wireguard_rollback_config')
    except subprocess.CalledProcessError:
        task_update_json(date, 'wireguard_rollback_config', 'fail')


# Revalida una configuración staging antes de copiarla al sistema.
# Revalidates a staging configuration before copying it to the system.
def _verify_conf(date, conf_path):
    try:
        # Fase única: validar sintaxis wg-quick antes de copiar al sistema.
        # Single phase: validate wg-quick syntax before copying to the system.
        _run(['wg-quick', 'strip', str(conf_path)])
        task_update_json(date, f'wireguard_apply_verify_{conf_path.stem}', 'success')
    except subprocess.CalledProcessError:
        task_update_json(date, f'wireguard_apply_verify_{conf_path.stem}', 'fail')
        raise SystemExit(1)


# Punto de entrada del commit para aplicar WireGuard con backup y rollback.
# Commit entry point to apply WireGuard with backup and rollback.
def apply_wireguard_config(user, date):
    # Leer el manifest generado para conocer el estado deseado.
    # Read the generated manifest to know the desired state.
    interfaces = _load_manifest(date)
    desired = {item['name']: Path(item['source']) for item in interfaces if isinstance(item, dict) and item.get('name') and item.get('source')}
    # Fase 2: detectar qué interfaces gestionadas existen actualmente en /etc/wireguard.
    # Phase 2: detect which managed interfaces currently exist in /etc/wireguard.
    active_managed = _active_managed_interfaces()
    all_managed = sorted(set(desired.keys()) | active_managed)

    # Si no hay WireGuard gestionado, no tocar servicios ni /etc/wireguard.
    # If there is no managed WireGuard, do not touch services or /etc/wireguard.
    if not desired and not active_managed:
        _success(date, 'wireguard_apply_config')
        _success(date, 'wireguard_verify_services')
        return

    # Verificar todos los archivos staging antes de modificar el sistema.
    # Verify every staging file before modifying the system.
    for iface, source in desired.items():
        if not source.exists():
            _fail(date, 'wireguard_apply_generated_exist')
        _verify_conf(date, source)

    # Crear backup de todo lo que se vaya a tocar para poder volver atrás.
    # Create a backup of everything that may be touched so rollback is possible.
    backup_dir, metadata = _backup_active(date, all_managed)
    if backup_dir is None:
        raise SystemExit(1)

    try:
        # Asegurar que existe /etc/wireguard antes de copiar archivos.
        # Ensure /etc/wireguard exists before copying files.
        _run(['sudo', 'mkdir', '-p', str(ACTIVE_DIR)])

        # Retirar interfaces gestionadas que ya no aparecen en el running JSON.
        # Remove managed interfaces that no longer appear in the running JSON.
        for iface in active_managed - set(desired.keys()):
            _run_allow_failure(['sudo', 'systemctl', 'stop', f'wg-quick@{iface}'])
            _run_allow_failure(['sudo', 'systemctl', 'disable', f'wg-quick@{iface}'])
            _run(['sudo', 'rm', '-f', str(ACTIVE_DIR / f'{iface}.conf')])
        # Instalar o actualizar cada interfaz deseada y reiniciar su servicio wg-quick.
        # Install or update each desired interface and restart its wg-quick service.
        for iface, source in desired.items():
            _run(['sudo', 'cp', str(source), str(ACTIVE_DIR / f'{iface}.conf')])
            _run(['sudo', 'chown', 'root:root', str(ACTIVE_DIR / f'{iface}.conf')])
            _run(['sudo', 'chmod', '0600', str(ACTIVE_DIR / f'{iface}.conf')])
            _run(['sudo', 'systemctl', 'enable', f'wg-quick@{iface}'])
            _run(['sudo', 'systemctl', 'restart', f'wg-quick@{iface}'])
            _run(['systemctl', 'is-active', '--quiet', f'wg-quick@{iface}'])
        _success(date, 'wireguard_apply_config')
        _success(date, 'wireguard_verify_services')
    except subprocess.CalledProcessError:
        # Si falla cualquier paso crítico, marcar fallo e intentar rollback.
        # If any critical step fails, mark failure and try rollback.
        task_update_json(date, 'wireguard_apply_config', 'fail')
        _rollback(date, backup_dir, metadata, all_managed)
        raise SystemExit(1)
