#!/usr/bin/env python3
"""
ES:
    Aplica de forma segura la configuración Apache del plano de gestión.

    Este script es el último paso del apply de Praesidium porque puede afectar
    directamente al acceso a la WebGUI. Lee el candidato generado en
    /var/lib/praesidium/running/praesidium_management_apache.conf, instala el site de
    gestión, deshabilita el site 000-default.conf cuando management gobierna
    Apache, ejecuta configtest y recarga Apache sólo si hubo cambios reales.

    Si algo falla, restaura el contenido y el estado de sites anterior para no
    dejar Apache en un estado intermedio.

EN:
    Safely apply Apache configuration for the management plane.

    This script is the last Praesidium apply step because it may directly affect
    WebGUI access. It reads the candidate generated at
    /var/lib/praesidium/running/praesidium_management_apache.conf, installs the
    management site, disables 000-default.conf when management owns Apache, runs
    configtest and restarts Apache only when real listener/site changes exist.

    If anything fails, it restores the previous site content and enabled/disabled
    state so Apache is not left halfway changed.
"""
from __future__ import annotations

import subprocess
from pathlib import Path

from task_update_json import task_update_json

# ES: Candidato generado por task_gen_management_apache.py.
# EN: Candidate generated by task_gen_management_apache.py.
CANDIDATE_PATH = Path('/var/lib/praesidium/running/praesidium_management_apache.conf')

# ES: Site Apache gestionado por Praesidium.
# EN: Apache site managed by Praesidium.
TARGET_PATH = Path('/etc/apache2/sites-available/praesidium-management.conf')
MANAGEMENT_SITE = 'praesidium-management.conf'
DEFAULT_SITE = '000-default.conf'

# ES: Rutas Debian/Ubuntu usadas por a2ensite/a2dissite/a2enmod.
# EN: Debian/Ubuntu paths used by a2ensite/a2dissite/a2enmod.
SITES_ENABLED = Path('/etc/apache2/sites-enabled')
SITES_AVAILABLE = Path('/etc/apache2/sites-available')
MODS_ENABLED = Path('/etc/apache2/mods-enabled')
PORTS_PATH = Path('/etc/apache2/ports.conf')


def _task(user: str, date: str, name: str, status: str) -> None:
    """
    ES: Registra una tarea en commit_history sin escribir en stdout.

    El endpoint PHP de commit espera que commit_apply.py devuelva un único JSON
    final. Por eso estas tareas internas no deben imprimir nada.

    EN: Register a task in commit_history without writing to stdout.

    The commit PHP endpoint expects commit_apply.py to return exactly one final
    JSON object, so these internal tasks must not print anything.
    """
    task_update_json(date, name, status)


def _run(cmd: list[str]) -> None:
    """
    ES: Ejecuta un comando del sistema y propaga el fallo con stdout/stderr capturado.
    EN: Run a system command and propagate failure with captured stdout/stderr.
    """
    subprocess.run(cmd, check=True, text=True, capture_output=True)


def _site_enabled(site_name: str) -> bool:
    """
    ES: Comprueba si un site Apache está habilitado mediante sites-enabled.
    EN: Check whether an Apache site is enabled through sites-enabled.
    """
    link = SITES_ENABLED / site_name
    return link.exists() or link.is_symlink()


def _site_available(site_name: str) -> bool:
    """
    ES: Comprueba si existe el archivo del site en sites-available.
    EN: Check whether the site file exists under sites-available.
    """
    return (SITES_AVAILABLE / site_name).exists()


def _ssl_enabled() -> bool:
    """
    ES: Comprueba si mod_ssl está habilitado sin ejecutar comandos.
    EN: Check whether mod_ssl is enabled without running commands.
    """
    return (MODS_ENABLED / 'ssl.load').exists()


def _apache_module_enabled(module: str) -> bool:
    """
    ES: Comprueba si un módulo Apache está habilitado mirando mods-enabled.
    EN: Check whether an Apache module is enabled by inspecting mods-enabled.
    """
    return (MODS_ENABLED / f'{module}.load').exists()


def _set_apache_module_enabled(module: str) -> bool:
    """
    ES: Habilita un módulo Apache sólo si aún no está activo.
    EN: Enable an Apache module only when it is not already active.
    """
    if _apache_module_enabled(module):
        return False
    _run(['a2enmod', module])
    return True


def _read_optional(path: Path) -> str | None:
    """
    ES: Lee un archivo si existe; devuelve None si no existe.
    EN: Read a file if it exists; return None when it does not.
    """
    return path.read_text(encoding='utf-8') if path.exists() else None


def _set_site_state(site_name: str, enabled: bool) -> bool:
    """
    ES:
        Fuerza el estado habilitado/deshabilitado de un site y devuelve si cambió.

        Usamos a2ensite/a2dissite en vez de borrar enlaces manualmente para respetar
        el flujo estándar Debian/Ubuntu y conservar rollback limpio.

    EN:
        Force an Apache site enabled/disabled state and return whether it changed.

        Use a2ensite/a2dissite instead of deleting symlinks manually to follow the
        standard Debian/Ubuntu flow and keep rollback clean.
    """
    current = _site_enabled(site_name)
    if current == enabled:
        return False

    if enabled:
        if not _site_available(site_name):
            raise FileNotFoundError(f'Apache site not available: {site_name}')
        _run(['a2ensite', site_name])
    else:
        # ES: a2dissite falla si el site no existe en sites-available; sólo lo llamamos si está habilitado.
        # EN: a2dissite fails when the site is not in sites-available; call it only when enabled.
        _run(['a2dissite', site_name])

    return True


def _set_ssl_enabled() -> bool:
    """
    ES: Habilita mod_ssl sólo si aún no está habilitado y devuelve si cambió.
    EN: Enable mod_ssl only if not already enabled and return whether it changed.
    """
    return _set_apache_module_enabled('ssl')


def _set_headers_enabled() -> bool:
    """
    ES: Habilita mod_headers para que Apache aplique las cabeceras Header always set.
    EN: Enable mod_headers so Apache can apply Header always set directives.
    """
    return _set_apache_module_enabled('headers')



def _set_fastapi_proxy_modules_enabled() -> bool:
    """
    ES:
        Habilita sólo si faltan los módulos Apache necesarios para ProxyPass.

        El puente WebGUI -> FastAPI vive en la configuración generada por
        task_gen_management_apache.py. Sin proxy/proxy_http Apache fallaría en
        configtest por directivas ProxyPass desconocidas.

    EN:
        Enable the Apache modules required by ProxyPass only when missing.

        The WebGUI -> FastAPI bridge lives in the configuration generated by
        task_gen_management_apache.py. Without proxy/proxy_http Apache would fail
        configtest because ProxyPass directives are unknown.
    """
    changed = False
    for module in ('proxy', 'proxy_http'):
        changed = _set_apache_module_enabled(module) or changed
    return changed



def _remove_global_listeners_from_ports() -> bool:
    """
    ES:
        Elimina Listen globales de /etc/apache2/ports.conf y devuelve si cambió.

        Praesidium management genera su propia directiva Listen con la IP exacta
        elegida en WebGUI, por ejemplo Listen 192.0.2.10:443. Si dejamos
        Listen 443 global en ports.conf, Apache intenta abrir *:443 y además
        IP:443 durante reload/restart; eso puede fallar con Address already in use.

        Por eso, cuando management gobierna Apache, ports.conf no debe declarar
        ni Listen 80 ni Listen 443. El único listener de management queda en
        praesidium-management.conf.

    EN:
        Remove global Listen directives from /etc/apache2/ports.conf and return
        whether it changed.

        Praesidium management generates its own Listen directive with the exact IP
        selected in WebGUI, for example Listen 192.0.2.10:443. If global
        Listen 443 remains in ports.conf, Apache may try to open *:443 plus IP:443
        during reload/restart and fail with Address already in use.

        Therefore, when management owns Apache, ports.conf must not declare either
        Listen 80 or Listen 443. The only management listener lives in
        praesidium-management.conf.
    """
    if not PORTS_PATH.exists():
        return False

    original = PORTS_PATH.read_text(encoding='utf-8')
    new_lines = []
    changed = False
    for line in original.splitlines(keepends=True):
        stripped = line.strip()
        # ES: Quitamos sólo listeners globales exactos; no tocamos comentarios ni otros puertos.
        # EN: Remove only exact global listeners; keep comments and other ports untouched.
        if stripped in {'Listen 80', 'Listen 443'}:
            changed = True
            continue
        new_lines.append(line)

    if changed:
        PORTS_PATH.write_text(''.join(new_lines), encoding='utf-8')
    return changed


def _restore_ports_conf(previous_content: str | None) -> bool:
    """
    ES: Restaura /etc/apache2/ports.conf para rollback.
    EN: Restore /etc/apache2/ports.conf for rollback.
    """
    current = _read_optional(PORTS_PATH)
    if previous_content is None:
        if PORTS_PATH.exists():
            PORTS_PATH.unlink()
            return True
        return False
    if current != previous_content:
        PORTS_PATH.write_text(previous_content, encoding='utf-8')
        return True
    return False

def _restore_file(previous_content: str | None) -> bool:
    """
    ES: Restaura el contenido anterior del site de gestión y devuelve si cambió.
    EN: Restore the previous management-site content and return whether it changed.
    """
    current_content = _read_optional(TARGET_PATH)
    if previous_content is None:
        if TARGET_PATH.exists():
            TARGET_PATH.unlink()
            return True
        return False

    if current_content != previous_content:
        TARGET_PATH.write_text(previous_content, encoding='utf-8')
        return True
    return False


def _restore_previous_state(previous: dict[str, object]) -> bool:
    """
    ES:
        Restaura el estado Apache previo al intento de apply.

        Sólo restaura lo que este script puede haber tocado: contenido del site
        Praesidium, site Praesidium habilitado/deshabilitado, site 000-default.conf
        habilitado/deshabilitado, mod_ssl, mod_headers, mod_proxy y mod_proxy_http si estaban deshabilitados antes.

    EN:
        Restore the Apache state that existed before the apply attempt.

        Restore only what this script may have changed: Praesidium site content,
        Praesidium site enabled/disabled state, 000-default.conf enabled/disabled
        state, and mod_ssl/mod_headers/mod_proxy/mod_proxy_http when they were disabled before.
    """
    changed = False
    changed = _restore_file(previous['target_content']) or changed
    changed = _restore_ports_conf(previous.get('ports_content')) or changed
    changed = _set_site_state(MANAGEMENT_SITE, bool(previous['management_enabled'])) or changed

    if _site_available(DEFAULT_SITE):
        changed = _set_site_state(DEFAULT_SITE, bool(previous['default_enabled'])) or changed

    # ES: Si habilitamos SSL durante el intento y antes estaba apagado, lo deshabilitamos en rollback.
    # EN: If we enabled SSL during the attempt and it was previously off, disable it during rollback.
    if not bool(previous['ssl_enabled']) and _ssl_enabled():
        _run(['a2dismod', 'ssl'])
        changed = True

    if not bool(previous.get('headers_enabled')) and _apache_module_enabled('headers'):
        _run(['a2dismod', 'headers'])
        changed = True


    # ES: Rollback de módulos proxy si sólo se activaron durante este intento.
    # EN: Roll back proxy modules if they were enabled only during this attempt.
    if not bool(previous.get('proxy_http_enabled')) and _apache_module_enabled('proxy_http'):
        _run(['a2dismod', 'proxy_http'])
        changed = True
    if not bool(previous.get('proxy_enabled')) and _apache_module_enabled('proxy'):
        _run(['a2dismod', 'proxy'])
        changed = True

    return changed


def _capture_state() -> dict[str, object]:
    """
    ES: Captura el estado Apache necesario para decidir cambios y hacer rollback.
    EN: Capture the Apache state needed to decide changes and perform rollback.
    """
    return {
        'target_content': _read_optional(TARGET_PATH),
        'ports_content': _read_optional(PORTS_PATH),
        'management_enabled': _site_enabled(MANAGEMENT_SITE),
        'default_enabled': _site_enabled(DEFAULT_SITE),
        'ssl_enabled': _ssl_enabled(),
        'headers_enabled': _apache_module_enabled('headers'),
        'proxy_enabled': _apache_module_enabled('proxy'),
        'proxy_http_enabled': _apache_module_enabled('proxy_http'),
    }


def _apply_enabled_candidate(user: str, date: str, candidate: str) -> None:
    """
    ES:
        Aplica el candidato activo del plano de gestión.

        Desired state cuando management enabled=true:
        - praesidium-management.conf instalado en sites-available;
        - mod_ssl y mod_headers habilitados;
        - 000-default.conf deshabilitado para que no compita en HTTP/80;
        - praesidium-management.conf habilitado;
        - restart de Apache sólo si algo de lo anterior cambió.

    EN:
        Apply the active management-plane candidate.

        Desired state when management enabled=true:
        - praesidium-management.conf installed under sites-available;
        - mod_ssl, mod_headers, mod_proxy and mod_proxy_http enabled;
        - 000-default.conf disabled so it does not compete on HTTP/80;
        - global Listen 80/443 removed from ports.conf so only the generated
          IP-specific HTTPS listener is active;
        - praesidium-management.conf enabled;
        - Apache restart only if any of the above changed.
    """
    previous = _capture_state()
    changed = False

    try:
        # ES: Escribir el site sólo si el contenido cambió evita reinicios innecesarios.
        # EN: Write the site only when content changed to avoid unnecessary restarts.
        if previous['target_content'] != candidate:
            TARGET_PATH.write_text(candidate, encoding='utf-8')
            changed = True

        changed = _set_ssl_enabled() or changed
        changed = _set_headers_enabled() or changed
        changed = _set_fastapi_proxy_modules_enabled() or changed

        # ES: Punto clave del bug: cuando Praesidium gobierna Apache, 000-default.conf no puede competir.
        # EN: Key bug fix: when Praesidium owns Apache, 000-default.conf must not compete.
        if _site_available(DEFAULT_SITE):
            changed = _set_site_state(DEFAULT_SITE, False) or changed

        # ES: Praesidium management queda sólo en su listener HTTPS IP:443 generado.
        # EN: Praesidium management stays only on its generated HTTPS IP:443 listener.
        changed = _remove_global_listeners_from_ports() or changed

        changed = _set_site_state(MANAGEMENT_SITE, True) or changed

        # ES: Validamos siempre la configuración, pero sólo recargamos si hubo cambios reales.
        # EN: Always validate the configuration, but restart only when there were real changes.
        _run(['apache2ctl', 'configtest'])
        _task(user, date, 'verify_management_apache_config', 'success')

        if changed:
            # ES: Usamos restart, no reload: los cambios de Listen pueden fallar en graceful reload
            #     por sockets antiguos todavía abiertos (Address already in use).
            # EN: Use restart, not reload: Listen changes may fail during graceful reload because
            #     old sockets can still be open (Address already in use).
            _run(['systemctl', 'restart', 'apache2'])
            _task(user, date, 'apply_management_apache_config', 'success')
        else:
            _task(user, date, 'apply_management_apache_config', 'success')

        _run(['systemctl', 'is-active', '--quiet', 'apache2'])
        _task(user, date, 'verify_management_apache_service', 'success')
        _task(user, date, 'apply_management_apache', 'success')

    except Exception:
        # ES: Rollback completo del estado previo si configtest/restart/validación falla.
        # EN: Full rollback to previous state if configtest/restart/validation fails.
        rollback_changed = _restore_previous_state(previous)
        _run(['apache2ctl', 'configtest'])
        if rollback_changed:
            # ES: Rollback de listeners/sites también requiere restart por seguridad.
            # EN: Listener/site rollback also requires restart for safety.
            _run(['systemctl', 'restart', 'apache2'])
        _task(user, date, 'apply_management_apache', 'fail')
        raise


def apply_management_apache(user: str, date: str):
    """
    ES: Punto de entrada llamado por main_task.py durante apply_config.
    EN: Entry point called by main_task.py during apply_config.
    """
    try:
        candidate = CANDIDATE_PATH.read_text(encoding='utf-8')
        _apply_enabled_candidate(user, date, candidate)
    except Exception:
        _task(user, date, 'apply_management_apache', 'fail')
        raise
